---
name: yamllint
"on":
  pull_request:
    branches: [ KFLUXDP-333 ]
  merge_group:
    types: [checks_requested]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint YAML files
        run: yamllint .
